package mpoljak.utilities;

/**
 * Ensures generating unique values within instance.
 * @param <T>
 */
public interface IGeneratorId<T> {
    /**
     * Generates ID that can be only once generated by this instance
     * @return unique ID within this generator instance
     */
    public T nextId();
}
